first challenge with quick_sort function
MIT-Emerging-Talent/2024-group-02-collaboration-practice pull request #18
Opened 2024-01-19 12:27 UTC by JumongEric

QuickSort is a popular and efficient sorting algorithm that follows the divide-and-conquer paradigm. The basic idea behind QuickSort is to select a "pivot" element from the array and partition the other elements into two sub-arrays according to whether they are less than or greater than the pivot. The process is then applied recursively to the sub-arrays.

2024-01-19 13:01 UTC, tvsirius commented
You should not have deleted the check list that was here

I will put it back

2024-01-19 13:01 UTC, tvsirius commented
- [ ] PR's title includes the challenge's name and language
- [ ] PR has short and clear description of the challenge
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] all conflicts are resolved (if any)
- [ ] It is linked to an issue in the appropriate column of the project board
- [ ] feedback is addressed (if any, and if it is appropriate feedback.)

## README Documentation

- [ ] The solution is documented in `/src/README.md`
- [ ] The markdown source is formatted
- [ ] Spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] All links and images work
- [ ] The README documents the solution's behavior, strategy(ies) and implementation(s)
- [ ] There are use cases in code blocks to illustrate the function's behavior

## Python Files

- [ ] There is a module header
- [ ] There is a module docstring
- [ ] File names are in snake_case
- [ ] Test files are named `test_<module_name>.py`

## Function Docstring

- [ ] Behavior description
- [ ] Parameter description
- [ ] Return value description
- [ ] Include any assumptions
- [ ] Include 3 or more (passing!) doctests
- [ ] Include 1-2 use cases (if necessary)

## Function Implementation

- [ ] The solution is not is not copied from [djeada](https://github.com/djeada/Algorithms-And-Data-Structures)
- [ ] The code is auto-formatted
- [ ] The code has no (reasonable) linting mistakes
- [ ] Variables are named with snake_case
- [ ] The function has a clear and helpful name
- [ ] The file's name matches the function name
- [ ] The code follows the strategy as simply as possible
- [ ] Variable names are clear and helpful
- [ ] Comments explain the strategy (if necessary)
- [ ] There are type annotations
- [ ] (challenge) The code includes defensive assertions

## Unit Test Suite

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Each unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases
- [ ] Test suite includes black-box and glass-box tests

2024-01-19 13:07 UTC, tvsirius commented
add README.md
add working test_quick_sort
when i pull your branch i have to fix it, 
with
```
from quick_sort import quick_sort
```

2024-01-19 13:14 UTC, tvsirius commented
Code is good and working, but it could be made better

You are missing:
module and test docstrings
type annotaions
comments marking zero case and it would be better to add coments on logic
use auto formatter (it's easy, just install autoPEP8 and press Shift-Alt-F in VSCode)

2024-01-19 17:55 UTC, tvsirius commented
Good, just fix the other issues

2024-01-20 10:14 UTC, tvsirius requested changes
Hey Eric, you solve most of my comments, but some left, that requires fixing
Please follow my comments

2024-01-20 10:14 UTC, tvsirius commented on src/sorting/python/quick_sort/src/quick_sort.py
> +            sequence= list(iterable)
WHY?! You will run sequence= list(iterable) in any case, why you use if-else

and it's not common to use try here, we use like
```
assert isinstance(iterable, (str,list,tuple,set)), "Input must be convertible to a list"
```

2024-01-20 10:14 UTC, tvsirius commented on src/sorting/python/quick_sort/src/quick_sort.py
> +def quick_sort(iterable):
type annotation please

2024-01-20 10:14 UTC, tvsirius commented on src/sorting/python/quick_sort/src/quick_sort.py
> +def quick_sort(iterable):
and a module docstring

2024-01-20 10:14 UTC, tvsirius commented on src/sorting/python/quick_sort/src/quick_sort.py
> +        return 'a','b', 'c', 'k' """
there is a format how to write doctest:
```
>>>quick_sort([3,2,5,7])
[2, 3, 5, 7]

>>>quick_sort(("back"))
['a', 'b', 'c', 'k']

2024-01-20 10:14 UTC, tvsirius commented on src/sorting/python/quick_sort/src/quick_sort.py
> +    return quick_sort(lower_items) + equal_items + quick_sort(upper_items)
looks like good, maybe some comments will add perfection

2024-01-20 18:17 UTC, JumongEric commented on src/sorting/python/quick_sort/src/quick_sort.py
> +            sequence= list(iterable)
Thanks, I appreciate your insight and help

2024-01-20 19:30 UTC, tvsirius approved these changes
Thats good, we can approve it to move on

Just no docsting and header for moudule (notes for future)
No docstrigns in test (but we speak with other team memebers and also find ok to not add them(
And look up my comment on doctest

Everything else is really good!

2024-01-20 19:30 UTC, tvsirius commented on src/sorting/python/quick_sort/src/quick_sort.py
> +        ['a','b', 'c', 'k'] """
look up how this is done in other examples.
you should not use such indent

2024-01-20 19:30 UTC, merged